### ISSUE TITLE
405 error when connecting to nextcloud webdav, issue with client->getAbsoluteUrl

### ISSUE THREAD

**Issue by kikkauz** [sabre-io/dav#1211] opened 2019-11-19 15:11 UTC
Hello

I'm trying to connect to a webdav fs exposed by a nextcloud instance.
Its uri is somthing like
https://my.nexcloudinstance.com/remote.php/webdav, as per nextcloud documentation.
however whey I try, for instance, to list a folder content, I get an error
 Sabre\HTTP\ClientHttpException  : Method Not Allowed

This comes from the getAbsoluteUrl that returns https://my.nexcloudinstance.com/
If I force this method to return the full uri, I get the list but all files and folders are prefixed with 
/remote.php/webdav

Best 

kikkauz

**Comment by DeepDiver1975** [comment] 2019-11-19 15:16
please report this to the nextcloud issue tracker or their forums.

**Comment by kikkauz** [comment] 2019-11-19 22:32
Hello

Sorry but I disagree. It’s the getAbsoluteUrl method of the client class that removes the path. The fact that it’s nextcloud is a detail. 

Kikkauz

**Comment by DeepDiver1975** [comment] 2019-11-19 23:19
So you are using sabre client to connect to nextcloud? This was no obvious in your description.
Please share the code base and we can have a second look

**Comment by kikkauz** [comment] 2019-11-20 07:13
Hello

Environment: Centos 7
PHP 7.2.22

I'm running the script via command line, so no webserver involved.
Code is very simple:
`
 $settings = [
            'baseUri' => 'https://my.nexcloudinstance.com/remote.php/webdav',
            'userName' => 'username',
            'password' => 'password'

        ];
        $davClient = new Client($settings);

        $folder_content = $davClient->propFind('/', array(
            '{DAV:}getlastmodified',
            '{DAV:}getcontenttype',
        ),1);
`
It returns a "Method Not Allowed" - 405 error.
Diggind deeped I noticed that the method getAbsoluteUrl of Sabre\DAV\Client returns
https://my.nexcloudinstance.com/ - without the path.
If I rewrite this method as simply
`function getAbsoluteUrl($url) {
        return $this->baseUri.$url;
    }`
I get a reply but all file paths are prefixed by /remote.php/webdav
For instance (print_r($folder_content)) :
`
[/remote.php/webdav/SHARED/] => Array
        (
            [{DAV:}getlastmodified] => Thu, 07 Nov 2019 19:17:58 GMT
        )

    [/remote.php/webdav/QC_INPUT/] => Array
        (
            [{DAV:}getlastmodified] => Tue, 19 Nov 2019 12:50:40 GMT
        )

    [/remote.php/webdav/QC_OUTPUT/] => Array
        (
            [{DAV:}getlastmodified] => Tue, 19 Nov 2019 12:50:40 GMT
        )
`

Could you please reopen the issue?
Best

Kikkauz

**Comment by evert** [comment] 2019-11-21 09:50
This is by design. getAbsolutePath() expands the path by the standard URL resolving algorithm, similar to a browser.

This would be similar to a website having a link to `<a href="/">` you would also expect that to resolve to the root of the domain, and concatenated with the base url.

If you just want to do the request on the base path, and not the root just use an empty string.

**Closed by evert** 2019-11-21 09:50 UTC
